<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ChartController' => 'controller/ChartController.php',
    'EmployeeWorkloadController' => 'controller/EmployeeWorkloadController.php',
    'ModifiedManiphestTaskGraph' => 'view/ModifiedManiphestTaskGraph.php',
    'ModifiedManiphestTaskResultListView' => 'view/ModifiedManiphestTaskResultListView.php',
    'ModifiedPHUIPropertyListView' => 'view/ModifiedPHUIPropertyListView.php',
    'ReportApplication' => 'application/PhabricatorReportApplication.php',
    'ReportController' => 'controller/ReportController.php',
    'TaskTreeController' => 'controller/TaskTreeController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ChartController' => 'PhabricatorController',
    'EmployeeWorkloadController' => 'PhabricatorController',
    'ModifiedManiphestTaskGraph' => 'PhabricatorObjectGraph',
    'ModifiedManiphestTaskResultListView' => 'ManiphestView',
    'ModifiedPHUIPropertyListView' => 'AphrontView',
    'ReportApplication' => 'PhabricatorApplication',
    'ReportController' => 'PhabricatorController',
    'TaskTreeController' => 'PhabricatorController',
  ),
));
