<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ChartController' => 'controller/ChartController.php',
    'EmployeeWorkloadController' => 'controller/EmployeeWorkloadController.php',
    'ModifiedManiphestTaskGraph' => 'graph/ModifiedManiphestTaskGraph.php',
    'ModifiedManiphestTaskResultListView' => 'view/ModifiedManiphestTaskResultListView.php',
    'ModifiedPHUIPropertyListView' => 'view/ModifiedPHUIPropertyListView.php',
    'ModifiedPhabricatorObjectGraph' => 'graph/ModifiedPhabricatorObjectGraph.php',
    'PhabricatorTasksDatasource' => 'typehead/PhabricatorTasksDatasource.php',
    'ReportApplication' => 'application/PhabricatorReportApplication.php',
    'ReportController' => 'controller/ReportController.php',
    'ReportingMissingCustomFieldException' => 'exception/ReportingMissingCustomFieldException.php',
    'TaskTreeController' => 'controller/TaskTreeController.php',
  ),
  'function' => array(
    'getCustomFieldValue' => 'utilities/CustomFieldUtilities.php',
  ),
  'xmap' => array(
    'ChartController' => 'PhabricatorController',
    'EmployeeWorkloadController' => 'PhabricatorController',
    'ModifiedManiphestTaskGraph' => 'PhabricatorObjectGraph',
    'ModifiedManiphestTaskResultListView' => 'ManiphestView',
    'ModifiedPHUIPropertyListView' => 'AphrontView',
    'ModifiedPhabricatorObjectGraph' => 'AbstractDirectedGraph',
    'PhabricatorTasksDatasource' => 'PhabricatorTypeaheadDatasource',
    'ReportApplication' => 'PhabricatorApplication',
    'ReportController' => 'PhabricatorController',
    'ReportingMissingCustomFieldException' => 'Exception',
    'TaskTreeController' => 'PhabricatorController',
  ),
));
